wikimedia-gadgets/afc-helper

- src/modules/core.js
All api submodules were merged into `mediawiki.api` in 1.33-wmf.16; avoids a console warning
Untested.
> core.js: Remove unnecessary api submodule imports

- src/modules/core.js
`getUTCMonthName` is a function from Twinkle's Morebits library (https://github.com/azatoth/twinkle) but it was deprecated (discussed at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_42#Technical_changes_2; see in particular https://github.com/azatoth/twinkle/pull/928 and https://github.com/azatoth/twinkle/pull/635).  The AFCH gadget doesn't actually import the morebits library, so in theory the presence of this was broken for anybody who wasn't a Twinkle user.
Note that `wgMonthNames` was slated to be removed (See https://github.com/azatoth/twinkle/issues/723 and https://phabricator.wikimedia.org/T219340) although it may be around for a while.  I *think* `Date.toLocaleString` can be used, but that's a bit weird tbh.  Alternatively, this gadget could be reworked to actually …
> core: Replace deprecated Morebits getUTCMonthName function

- src/modules/submissions.js
Restrict requiring the presence of an AfC submission template to userspace
Per https://en.wikipedia.org/wiki/WP:G13, "Any pages that have not been edited by a human in six months found in:
1. Draft namespace
2 Userspace with an {{AFC submission}} template...
There is no requirement that pages in the _draft_ namespace have an AfC template (be submitted and rejected) before they can be deleted.
> Allow G13 on unsubmitted drafts

- src/modules/submissions.js
This silly comment keeps changing. This patch covers the current version generated by [Template:AfC preload/draft](https://en.wikipedia.org/wiki/Template:AfC_preload/draft). See [Draft:Begin Yoshioka](https://en.wikipedia.org/wiki/Draft:Begin_Yoshioka) for an example picked at random (the dreaded "long comment" warning).
> Expand inline citation comment regex

- src/afch.js
disable helper script for all of Wikipedia: and Wikipedia talk: namespace except for on AfC/sandbox. Running the helper script on WP:AFC pages and subpages is redundant for now given that drafts are now at Draft: namespace. should fix #133 as well.
> disable helper script on WP/WPT pages sans AfC/sandbox

- src/modules/submissions.js
- src/templates/tpl-submissions.html
A possible solution to #145
I've decided to take a look at this issue and was able to come to a working solution. I've taken a different approach from the proposed solution so the code becomes more consistent with the comments: in them, it is implied that the textarea is hidden if there's no selected reason, so I've changed the textarea to be hidden by default and to toggle with the other elements.
Please let me know if this approach makes sense or if further changes are necessary.
https://user-images.githubusercontent.com/16337001/130522516-af6d5b9e-9e45-4e73-9471-95e3d6c4ea8c.mp4
> Hide decline button when no reason is selected

- src/modules/submissions.js
getting a good testcase for this is tricky as CopyPatrol folks appear to be quick to fix copyvios, and once fixed this warning will not be shown. 
But you could hack in `mw.config.get( 'wgCurRevisionId', json.pagetriagelist.pages[ 0 ].copyvio )` in the code to see the warning.
Closes #194
> show copyvio warning

- src/modules/core.js
'edit' and 'options' token types are deprecated in favour of csrf token. Have used the function postWithEditToken() here that uses csrf token - which should be more stable and forward-compatible than using `postWithToken( 'csrf', ... )`.
> Avoid use of deprecated token types

- src/modules/submissions.js
also a cosmetic 2nd commit that changes all `'~~' + '~~'` to `~~~~`.
Closes #167.
> Remove {{promising draft}}, and unify template removal logic

- src/modules/submissions.js
- src/templates/tpl-submissions.html
Values entered here have been unused since persondata was removed in https://github.com/WPAFC/afch-rewrite/commit/9632e4fd (2015).
Discussion in #190.
> Remove acceptance form fields whose values aren't used

- src/modules/submissions.js
I've fixed the comment preview so it works with custom signatures. I also made it so the preview is hidden after the text box is cleared, solving [this issue](https://github.com/WPAFC/afch-rewrite/issues/216).
> Fix comment preview

- src/modules/submissions.js
This fixes https://github.com/WPAFC/afch-rewrite/issues/103 by adding missing parentheses to Line 2559 so that the part before "isDecline ? 'declined' : 'rejected'" correctly appears in the edit summary.
> Add missing parentheses to Line 2559 to fix #103

- src/modules/submissions.js
Fix #238
Also change from "get" to "post" to prevent a large # of templates from hitting the max URL length (2048 characters)
> fix toomanyvalues API error

- .github/workflows/unit_tests.yml
- .travis.yml
- README.md
- STYLEGUIDE.md
Unit test continuous integration (where the unit tests are run with every PR or commit, and a green check mark or red X displays depending on whether the unit tests pass or fail) is not currently working.
There may be a way to fix Travis CI, but this patch instead replaces Travis CI with GitHub Actions. That way everything is under one roof, which should be easier for maintainability.
Having unit tests + CI is an important bump to the maintainability of any project.
Unable to fully test since CI hasn't run on this PR yet. But this should get us started. I'll do a follow up PR, if needed.
> switch to GitHub Actions continuous integration

- src/modules/submissions.js
Requested by Slywriter at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#AFCH%3A_next_%22very_old%22_submission
The "next very old submission" category is always empty, since we never have drafts older than 6 months. So no need to market the link in such a high profile place. If folks want to visit this category, they can do so via https://en.wikipedia.org/wiki/Template:AfC_pending_submissions_by_age_(category_header) or similar
Before:
After:
> remove "next very old submission"

- src/modules/submissions.js
Fixes issue #202, where the copyvio URL would not be shown if the option for speedy deletion wasn't selected. I've tested it and it works fine, see the below image for an example.
> Show copyvio url when not selecting speedy deletion

- src/modules/core.js
- src/modules/submissions.js
I set a AFCH.const.userSysop and checked against that. Obviously I'm not an admin and testwiki lets anyone use the script anyway, so this hasn't been tested except to confirm that AFCH.const.userSysop returns false for me.
I assume it's fine to take this issue given that the person assigned it hasn't commented there in a year, but let me know if this is some kind of horrible etiquette violation.
> Allow admins to use the script (#130)

- src/modules/core.js
- src/modules/submissions.js
- src/templates/tpl-preferences.html
Resolves #134. Off by default, if enabled in preferences logs. Currently logs everything on one page with headers for the month, which might be inconvenient for really prolific reviewers.
Message for decline:
> \n# Declined [[:Title]] (reason1 & reason2) by [[User:Username|]] ~~~~~\n
Message for accept/reject:
> \n# [Accept/reject]ed [[:Title]] by [[User:Username|]] ~~~~~\n
> Userspace log of drafts

- src/modules/submissions.js
~~Fixes 215~~
Adds 1-week expiration date for cached WikiProject list to match 1-week expiration schedule (the current code only refreshes the cache when the version number is updated, and it never actually removes the old cache which can cause the localstorage quota to fill up).
> Expire WikiProjects list after 1 week

- .gitignore
When deploying, you need to install pywikibot. Need to gitignore these to not clutter up the repo.
> gitignore pywikibot files and folders

- src/modules/core.js
- src/modules/submissions.js
- tests/scaffold.js
- tests/test-core.js
Fix #245
This new code is vulnerable to deleting the wrong heading if someone puts a category in the wrong place (not at the bottom of the article), but I think that's an acceptable tradeoff for now. If it actually affects someone we can make the solution more complex in a future patch.
> fix regex catastrophic backtracking

- package.json
- src/modules/submissions.js
Very small PR just to make sure I understand how everything works before I try to handle any of the outstanding issues: when accepting a biography, autofills name when there is a parenthetical disambiguation and otherwise the title looks to be Firstname Lastname. (Also, my IDE took umbrage with package.json's testMatch having two entries on one line and decided to fix it for me, which I haven't undone because it seems like a reasonable formatting change. Happy to undo it if that's a problem.)
> Update biography DEFAULTSORT autofill to work with paranthetical disambiguation

- src/modules/submissions.js
CopyPatrol has moved from copypatrol.toolforge.org to copypatrol.wmcloud.org.
> update CopyPatrol URL from toolforge.org to wmcloud.org

- src/modules/submissions.js
> when accepting a draft, change user talk edit summary to wikilink to the draft, not to [[WP:AFC]]

- src/modules/core.js
Fixes #90
Advantages
- Simpler than patch #291
- The original intent of the function notifyUser was to follow redirects, indicated by the comment "Follows redirects and appends a message to the bottom of the user's talk page." from 2014. So this fixes that bug.
Disadvantages
- Will only follow 1 redirect, not 2+ redirects.
- The "Saved [[User talk:OldUsername]] (diff)" message shown to the AFC reviewer will be slightly incorrect. The diff will be correct, but OldUsername should ideally be NewUsername.
> Follow redirects when notifying users

- src/modules/submissions.js
> Recursively identify renamed username of submitter

- src/modules/core.js
- src/modules/submissions.js
- tests/test-core.js
- Extract all code related to adding WikiProject banners to the draft talk pages to its own function. Goal is to get this "wikicode in -> wikicode out" style code to be unit testable, in preparation for [future work](https://github.com/wikimedia-gadgets/afc-helper/issues?q=is%3Aissue+label%3Adraft-talk-page-wikitext+).
- Add some unit tests.
Should be a no-op.
> refactor adding talk page banners

- src/less/submissions.less
- src/modules/submissions.js
- add parentheses around them
- scoot the link a bit farther away from the warning message
Before:
After:
> make warning links prettier

- src/modules/submissions.js
fix #105
This is the same approach used by the "decline" form, which hides the submit button until decline reasons are chosen.
> hide submit button if no comment typed in

- src/less/submissions.less
- src/modules/core.js
- src/modules/submissions.js
- src/templates/tpl-submissions.html
- Only checks when the submit button is clicked, to avoid spamming the Wikimedia API.
- When an edit conflict is detected, hides the submit button and displays a red warning message with a link to the draft's edit history.
- Does not allow a user to continue if an edit conflict is detected, forcing the user to reload the page. This is because continuing anyway would overwrite the previous edit.
- Doesn't currently save any form data on refresh, which would require more code and potentially be complicated to store and reload the entire state of a complex form like the decline form. Hopefully the user is smart enough to Ctrl-C if they typed a bunch of stuff into the comment box.
Fixes #153
> add edit conflict detection

- src/modules/submissions.js
change "reloaded automatically" to "reload"
It doesn't auto refresh the page for you. You have to click the link. So "reloaded automatically" is factually incorrect.
> change "reloaded automatically" to "reload"

- src/modules/submissions.js
Fixes a bug reported by DoubleGrazing at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Commenting_causes_'edit_conflict'
> don't detect own edits as edit conflict

- src/modules/submissions.js
Reverts wikimedia-gadgets/afc-helper#352
Has a bug where edits that shouldn't be are being detected as edit conflicts. Maybe even all edits.
Steps to reproduce:
* go to a draft that isn't submitted
* try to submit
> Revert "don't detect own edits as edit conflict"

- src/modules/core.js
- tests/test-core.js
requested at WT:AFC. makes it more readable when there's multiple parameters
> core: add |1= to {{WikiProject banner shell}}

- .eslintignore
- .eslintrc.json
- src/afch.js
- src/modules/core.js
- src/modules/submissions.js
- tests/scaffold.js
- tests/test-core.js
Why
- Running old JS code through the mediawiki linter improves code quality and maintainability
- We can fully embrace ES6 now. The MediaWiki/Wikimedia compatibility policy allows it. We don't need to limit ourselves to ES5.
What
- add more eslint-config-wikimedia rules
- apply autofixes
- set un-autofixed errors to warn or off
- add server.js to .eslintignore since I couldn't figure out how to handle that error
> add more eslint-config-wikimedia rules. apply autofixes

- src/modules/core.js
- src/modules/submissions.js
- src/templates/tpl-submissions.html
- tests/test-core.js
- in wikicode, on draft talk pages, capitalize article assessments such as Start, Stub, etc.
- Evad37/rater.js does this. Let's copy this practice, so that rater diffs are smaller. For example, the conversion of |class=start to |class=Start in this diff could have been avoided if AFCH had just written |class=Start in the first place: https://en.wikipedia.org/w/index.php?title=Talk:Phare_Circus&diff=next&oldid=1242207529
- when AFC accepting a stub, allow StubSorter user script to load on testwiki. for easier testing
- when writing template syntax, place a space before pipes. this is also to copy rater.
- fix a bug in the duplicate template detection algorithm. it will now handle a space at the end of the template name
> improve wikicode writing to draft talk pages

- src/modules/core.js
- tests/test-core.js
instead of in {{WikiProject Biography}}
> addTalkPageBanners: |living= and |listas= go in banner shell

- .eslintrc.json
- tests/scaffold.js
- tests/test-core.js
* fix some linter errors in scaffold.js
* get rid of requireScript() function because it triggered a security linter warning
> tests: fix linter errors in scaffold.js

- src/modules/core.js
- tests/test-core.js
> addTalkPageBanners: fix |class={{{class}}} bug

- src/templates/tpl-submissions.html
Add cat - submission is a category decline option. Will shortly open a edit-request at https://en.wikipedia.org/wiki/Template_talk:AfC_submission/comments as well for the comment update.
Fixes #363
> Add cat - submission is a category decline option

- src/modules/submissions.js
- tests/test-submissions.js
- handle hidden comment ``. this is the new wording. also keep handling the old wording for backwards compatibility
- handle hidden comment ``. i ran across this when researching this ticket and it is also common
- add tests
- refactor
- let to const
- move nested function convertExternalLinksToWikilinks() to top level
- change jQuery $.merge() to native .push()
Fixes #410
> submission.js cleanUp(): handle 2 more types of hidden comments, refactor

- .eslintignore
- .gitignore
- package-lock.json
- package.json
- scripts/credentials.example.json
- scripts/deploy.js
- src/afch.js
- src/modules/core.js
To use, create the file `scripts/credentials.json` with the following format:
```
{
"site": "http://localhost:4000/api.php",
"username": "Wikiuser@bp5",
"password": "12345678901234567890123456789012"
}
```
Replacing the values as necessary. Alternatively, the parameters can be specified via cli params (`--site`, `--username`, `--password`). Authentication via OAuth2 access token (`--accessToken`) is also supported to facilitate running automatically via a web frontend in the future.
Then run `node scripts/deploy.js` (or use the shortcut `npm run deploy`). Full cli documentation is available with the script's `-h`/`--help` flag.
Closes #413
> Rewrite deployment script in node.js

- src/afch.js
Removing sandbox check because that sandbox page is old and just redirects to WP:AFC. This also lets us simplify our namespace checking down to 2 namespaces.
Adding a comment about ResourceLoader now doing some namespace checking, and why we're keeping this namespace checking code.
I changed MediaWiki:Gadgets-definition to do the namespace check in https://en.wikipedia.org/w/index.php?title=MediaWiki:Gadgets-definition&diff=prev&oldid=1297769296 and https://test.wikipedia.org/w/index.php?title=MediaWiki:Gadgets-definition&diff=prev&oldid=664605
Related #415
> afch.js: remove sandbox check & update comment

- jest.config.js
- package.json
Moving existing config from package.json to jest.config.js, since all config need to be in the same place, and package.json doesn't support conditional logic.
Solves #427
> jest: set maxWorkers = 1 when running in deploy service

- .github/workflows/linter.yml
Should fix the below screenshot, bringing the number of CI checks on each PR from 3 to 2.
> ci: don't run the linter task twice in PRs

- Gruntfile.js
- package-lock.json
- package.json
- src/less/general.less
- src/less/minimal.less
* Remove grunt-autoprefixer
* The only CSS rule requiring vendor-prefixing is user-select: none. It's supported everywhere except for Safari which needs the -webkit- prefix. Added it manually and removed the grunt-autoprefixer dependency. All other CSS being used in the gadget is standard.
* Remove css minification
* Remove grunt-cssmin dependency. CSS minification is unnecessary in the build as it anyway gets handled by ResourceLoader. This also makes the on-wiki CSS file readable.
* Remove minimal.less: empty and unused
> Remove minification and vendor-prefixing while building LESS files
