wikimedia-gadgets/afc-helper

- scripts/upload.py
Changing “WindowsError” To “OsError” due to errors on a Mac
> Change "WindowsError" to "OSError"

- src/modules/core.js
- src/modules/submissions.js
Updated version of https://github.com/WPAFC/afch-rewrite/pull/28 per comment at https://github.com/WPAFC/afch-rewrite/pull/28#issuecomment-64842043
I had to create a new pull request because there doesn't seem to be a way to update a fork from the web interface without deleting and creating a new fork.
>  Include oldid field in {{db-g12}} 

- src/modules/submissions.js
Per https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Reviewer_comments_lost_on_creation_of_the_article
> Support oldid parameter in {{WPAFC/article}}

- .travis.yml
- Gruntfile.js
- package.json
- src/modules/submissions.js
* All devDependencies have been updated, expect `jest-cli` which has been upgraded several versions, but held back due to errors with the latest version.
* Several files have been slightly cleaned up in the process.
> Repair Travis intergration.

- src/modules/submissions.js
Use the same data source as https://en.wikipedia.org/wiki/MediaWiki:AFC-add-project-tags.js for consistency
> Fetch Wikiproject list from [[Wikipedia:WikiProject_Articles_for_creation/WikiProject_templates.json]]

- src/modules/core.js
- src/modules/submissions.js
Mark cleanup-only edits as minor edits per  #178
> Mark cleanup-only edits as minor edits

- src/modules/submissions.js
Also remove https://en.wikipedia.org/wiki/Template:AfC_topic template when accepting AfC submission.
> Also remove {{AfC topic}} template

- server.js
@enterprisey, I have changed the server.js file, and now it does not requires the upload of certificates in the browser
fixes #203
> replaced https with http

- src/less/submissions.less
- src/modules/submissions.js
- src/templates/tpl-submissions.html
Live preview is helpful in preventing issues like linking to red-linked page, etc.
> Show live preview while writing comments

- src/modules/submissions.js
> Handle slashes in article titles

- src/less/submissions.less
- src/modules/submissions.js
- src/templates/tpl-submissions.html
As requested https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:WikiProject_Articles_for_creation&diff=1066284130
NOTE: Not yet fully tested.
> Show live preview for decline/reject reasons

- package.json
> remove JS dependency "minimist"

- .gitignore
- package-lock.json
> add package-lock.json to repo

- src/templates/tpl-submissions.html
> Add [[WP:NEVENT]]

- src/modules/core.js
- src/modules/submissions.js
> Provide Template:L with 'MISSING' as second parameter if date is omitted

- package-lock.json
- package.json
> update organization and repo name in package.json

- src/modules/submissions.js
> copy comments to talk page: add line breaks before heading

- package.json
> fix repo URL in package.json

- src/modules/submissions.js
fix #324
Was comparing string to int. One fix is to change `===` to `==`
> fix displaying "This submission may contain copyright violations"

- tests/test-core.js
to increase code coverage of a function I plan to refactor
> add test for lifeStatus = dead

- .gitignore
> gitignore: add apicache

- src/modules/core.js
- tests/test-core.js
should be placed in the banner shell
> core: fix detection of {{OKA}} banner

- src/modules/core.js
- tests/test-core.js
requested at WT:AFC for historical reasons
> core: place WPAFC banner first

- src/modules/submissions.js
> submission: change talk page edit summary

- src/modules/submissions.js
Fixes #367
This corresponding edit to Template:AfC contribution makes this patch work: https://en.wikipedia.org/w/index.php?title=Template%3AAfC_contribution&diff=1241908041&oldid=619305950
Example. Bullet 1 is what it will look like with this patch. Bullet 2 is what it currently looks like without.
> submission: add reviewer to WP:AFC/recent

- src/modules/core.js
- tests/test-core.js
https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:WikiProject_Articles_for_creation&curid=11547670&diff=1243669976&oldid=1243646954
> addTalkPageBanners: don't write a class if the shell auto detects it

- tests/scaffold.js
* functions on top
* get rid of a = b = c, which I find confusing to read. had to look it up
* rename fs to fileSystem, which is clearer
> scaffold: refactor

- src/modules/submissions.js
> expand wording of page-salted error message
